# Generated by Django 4.0.5 on 2022-07-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options_alter_movie_kinopoisk_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='kinopoisk_id',
            new_name='magnet_link',
        ),
    ]
