# Generated by Django 4.0.5 on 2022-07-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_magnet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
