# Generated by Django 4.0.5 on 2022-07-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_country_movie_director_movie_genre_movie_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='number',
        ),
    ]
