# Generated by Django 4.0.5 on 2022-07-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slogan',
        ),
    ]
