# Generated by Django 4.0.5 on 2022-07-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_number_movie_slogan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='number',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='slogan',
        ),
    ]
